#!/usr/bin/env bash

# File permissions for templates.
# In the same format as chmod.
# `chmod "${perms[EXT]}" file.EXT` will be performed.
perms=(
  [py]=755
  [sh]=+x
# [EXT]=PERMS
)
export perms

# Set the content of the variables here
# To add a new line, just put a carriage
# return in the quotes. \n does not work.
DATE="$(date)"
export DATE
export AUTHOR="Your name here"
export CPP_HEADER="#include <iostream>"
export C_HEADER="#include <stdio.h>"
export C_MODELINE="/* vim: set ts=4 sts=4 sw=4 et : */"
export MAKE_CC="gcc"
export MAKE_CFLAGS="-Wall -g -Werror -pedantic"
export MD_MODELINE="
<!-- ltex: language=fr -->
<!-- ltex: enabled=true -->
<!-- vim:set ts=4 sts=4 sw=4 et: -->"
export PY_MODELINE="# vim: set ts=4 sts=4 sw=4 noet :"
export SH_MODELINE="# vim:set ts=2 sts=2 sw=2 et:"

# vim:set ts=8 sts=2 sw=2 et syn=sh:
